#!/bin/bash

cd tests 2>/dev/null || cd ../tests 2>/dev/null || exit 1

red="\x1b[2K\r\x1b[38;5;203m"
green="\x1b[2K\r\x1b[38;5;112m"

for filename in *.js; do
    if [[ ! "$filename" =~ "jsbm" ]]; then
        name="\x1b[1m${filename//.js/}\x1b[0m"
        echo -ne "running tests $name"
        node "$filename" && echo -ne "${green}success $name\n" || echo -ne "${red}failed $name\n"
    fi
done
